# These are supported funding model platforms

github: [petertam]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: 
issuehunt: petertam 
otechie: wapeter
custom: [https://github.com/petertam/vim-rus-phonetic]
